name: Honey Ledger App Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder:latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v4

      - name: Build Honey Ledger App (Nano S Plus)
        run: |
          make clean || true
          make TARGET_NAME=nanosplus
